### ISSUE TITLE
Classes vs Ids

### ISSUE THREAD

**Issue by Tereseus** [pshirvaikar/prj-rev-bwfs-dasmoto#2]
I like how you named your div ids but you should use classes for the css. Why you ask? Well each section basically has similar css, what is inside the section is different but the display: block applies to Brushes, Frames and Paint. So what you could do is create a class called item which each div will take as a class. Just using item will make your css file shorter and save you the time of having to apply display block to every individual div. Then you can make ids for the h2 tags where you can apply the background color for Brushes, Frames and Paint. Not a major issue either just a way to write less code.

**Comment by pshirvaikar** [comment]
What element would the item class be attached to? How can I do this? Thanks
